void sendMessage(char* msg);
void setNickname(char* nick);
void setUser(char* nick);
void joinChannel(char* channel);
void partChannel(char* channel);
void listOptions(char* channel);
void enterCalculatorMode(char* channel);
void listCalculatorOptions(char* channel);
void add(char* channel, int toBeAdded);
void subtract(char* channel, int toBeSubtracted);
void multiply(char* channel. int toBemultiplied);
void divide(char* channel. int toBeDivided);
void equal(char* channel. int toBemultiplied);
void clear(char* channel);
void quitIRC(char*);
void sendChat(char* channel, char* toSend);
void setMsgHandler(void (*funPtr)(char*, char*, char*));
void initConnect(char* ip);
void cleanup();
